name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install and test server
        run: |
          cd server
          npm install
          npm test
          
      - name: Install and test client
        run: |
          cd client
          npm install
          npm test
